### ISSUE TITLE
get_setting() -- Missing Argument & Undefined Variable

### ISSUE THREAD

**Issue by maxledoux** [deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks#10]
I uncommented:
```php
add_action( 'as3cf_setting_object-prefix', array( $this, 'get_setting' ), 10, 2 );
```
And customized the prefix:
```php
	function get_setting( $key, $value ) {
		if ( 'object-prefix' == $key ) {
			$value = '/my-folder/';
		}

		return $value;
	}
```

When I upload a file, these errors are generated:
```
PHP Warning:  Missing argument 2 for Amazon_S3_and_CloudFront_Tweaks::get_setting() in /site/wp-content/plugins/amazon-s3-and-cloudfront-tweaks/amazon-s3-and-cloudfront-tweaks.php on line 62
PHP Notice:  Undefined variable: value in /site/wp-content/plugins/amazon-s3-and-cloudfront-tweaks/amazon-s3-and-cloudfront-tweaks.php on line 67
```

The file ends up on Amazon S3, but instead of being in `bucket/my-folder/2017/03/file.ext` it is at `bucket/2017/03/file.ext`

**Comment by ianmjones** [comment]
Sorry about that, looks like the example is wrong, it should be a setting specific function which takes and returns the setting value only.

I've updated the plugin, please download again.

**Comment by maxledoux** [comment]
I'm confirming this is working on my end now.

Thank you!
