### ISSUE TITLE
Adding a bunch of characters to the upoad file url

### ISSUE THREAD

**Issue by mrekemini** [deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks#14]
I noticed that after the recent update of **WP Offload S3 Lite** plugin, it's been adding characters to the upload url like; https://DomainName.com/wp-content/uploads/2017/12/filename.mp3?AWSAccessKeyId=AKIAI3JPXIWEN5B7F76HA&Expires=1512029711&Signature=7D1GckgIi6zfEcdHqMHH37G8jpv3D

Please note, the extra added characters after **/filename.mp3?** above

**Comment by aaemnnosttv** [comment]
This is a signed URL generated by the plugin to provide temporary access to a private file on S3 (usually a product download file). Were you previously using the non-Lite version on your site before switching to the Lite version?

**Comment by mrekemini** [comment]
I've been using Lite version all along for the past 2months or so with 'normal' url that typically ends with the file extension (e.g. .mp3). I just noticed this changes after the recent update of the Lite plugin that when the tweak plugin is enabled, it adds the extra characters to the file path.

**Comment by aaemnnosttv** [comment]
Can you attach your `amazon-s3-and-cloudfront-tweaks.php` file here so we can see what tweaks you're using and how? (You can just drag the file onto the comment box)

**Comment by mrekemini** [comment]
Here it is. Sorry I was offline for the weekend

**Comment by mrekemini** [comment]
[amazon-s3-and-cloudfront-tweaks.zip](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks/files/1527045/amazon-s3-and-cloudfront-tweaks.zip)

**Comment by aaemnnosttv** [comment]
You're using the `as3cf_upload_acl` filter to override the ACL for all uploaded media items to be `private`. This is why you're seeing signed URLs on all your media and is expected behavior for private media items served by Offload S3.

**Comment by mrekemini** [comment]
Oh ok... my reason for using this plugin was to make link to all mp3 files download automatically instead of loading/playing the audio on the browser.
I guess `as3cf_object_meta` does the trick. Please correct me if I'm wrong

**Comment by ianmjones** [comment]
@mrekemini Yes, you can use the `as3cf_object_meta` filter to add a "ContentDisposition" element to the array with value "attachment" and that should make the file download rather than play in the browser.

You might need to add a "ContentType" element with value "application/octet-stream" too, but don't do that unless necessary.
