### ISSUE TITLE
WP All Import Compatibilty

### ISSUE THREAD

**Issue by samisaboss** [deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks#21]
Hi, 

I have a property site that using WP All Import to add the properties. 
I developed a custom add on to write EXIF Metadata to the properties image. 
Basically, It only get all resized image and write the EXIF directly into the filepath(Overwrite). 
This code are hooked into "pmxi_saved_post" event that WP All Import will trigger on every successful post created/updated.

Everything is fine before. Then I decide to use WP Offload Media plugin and did some import. 
The EXIF Meta blank in my S3 bucket. 

Is there any way to achieve this? What hook should I use? I was thinking that "pmxi_saved_post" action triggered too late.

**Comment by ianmjones** [comment]
Please send us a support request via WP Offload Media's Support tab and we'll try and help.
