### ISSUE TITLE
Remove the 'sites/{blog_id}' prefix for multisite media path

### ISSUE THREAD

**Issue by Mike-Antipov** [deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks#25]
I need to turn off auto-appending part of the 'get_dynamic_prefix' function: `$prefix = '/sites/' . get_current_blog_id()`. Is that possible without modifying the plugin?

**Comment by ianmjones** [comment]
Hey @Mike-Antipov, is this a multisite migrated from pre WP3.5?

If so, does the following help...

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks/blob/beb2e0f1bba71be7b462a60209e5ff630a57437e/amazon-s3-and-cloudfront-tweaks.php#L564

If not, can you give us a little more context?

**Comment by Mike-Antipov** [comment]
Hey @ianmjones, it's a fresh install of the latest WP version, I need to store all media files for a particular site in one particular folder and I don't need, e.g, the 'sites/2' folder to be created, is that an option?

**Comment by ianmjones** [comment]
> Hey @ianmjones, it's a fresh install of the latest WP version, I need to store all media files for a particular site in one particular folder and I don't need, e.g, the 'sites/2' folder to be created, is that an option?

Not an option, and not advised as you'll very likely ultimately end up with clashes of object keys across sites if you're not careful, but you can override the object key with the `as3cf_object_meta` filter.

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks/blob/beb2e0f1bba71be7b462a60209e5ff630a57437e/amazon-s3-and-cloudfront-tweaks.php#L681

**Comment by Mike-Antipov** [comment]
> Not an option, and not advised as you'll very likely ultimately end up with clashes of object keys across sites if you're not careful, but you can override the object key with the `as3cf_object_meta` filter.
> 
> https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks/blob/beb2e0f1bba71be7b462a60209e5ff630a57437e/amazon-s3-and-cloudfront-tweaks.php#L681

But that will corrupt thumbnails, right? The idea here is to rename 'sites/$blog_id' to some another unique name, e.g., use a domain name instead.

**Comment by ianmjones** [comment]
> But that will corrupt thumbnails, right?

No, not these days. Once upon a time changing the offload path via this filter would not also change the path for thumbnails being offloaded with it, but that changed a long time ago.

> The idea here is to rename 'sites/$blog_id' to some another unique name, e.g., use a domain name instead.

Yes, you could easily substitute in a different path with the `as3cf_object_meta` filter that removes the standard multisite segment and instead uses a cleaned up domain name.
