### ISSUE TITLE
 How can I add noindex/index to offloaded s3 object?

### ISSUE THREAD

**Issue by bhaktvanti** [deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks#30]
This isn't working! Any help appreciated. Thank you!

```
function custom_upload_to_s3($args, $post_id, $image_size, $copy) {
    // Initialize the 'x-robots-tag' if not set
    if (!isset($args['x-robots-tag'])) {
        $args['x-robots-tag'] = [];
    }

    // Get the 'searchable' custom field value
    $searchable = get_field('searchable', $post_id);

    // Get the file extension
    $extension = pathinfo($args['Key'], PATHINFO_EXTENSION);

    // Check if the file is a PDF
    if (in_array($extension, array('pdf'))) {
        if ($searchable) {
            // If searchable, set the robots tag to 'index, follow'
            $args['x-robots-tag'] = "index,follow";
        } else {
            // If not searchable, set the robots tag to 'noindex, nofollow'
            $args['x-robots-tag'] = "noindex,nofollow";
        }
    }

    // Debug logging
    error_log("custom_upload_to_s3: post_id={$post_id}, extension={$extension}, searchable={$searchable}, x-robots-tag={$args['x-robots-tag']}");

    return $args;
}
add_filter('as3cf_object_meta', 'custom_upload_to_s3', 10, 4);
```

**Comment by ianmjones** [comment]
The `as3cf_object_meta` filter allows you to alter the parameters passed to the `PutObject` AWS SDK command, `x-robots-tag` is not a parameter.

https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#putobject

If you look at the parameters in the above doc, you'll see there are a few common HTTP headers that have been added as parameters (e.g. `content-disposition` is available as `ContentDisposition`), but not many.

To add any other headers, or rather metadata, you can add entries to the `Metadata` parameter.

`$args['Metadata']['x-robots-tag'] = 'noindex,nofollow';`

I'm not sure whether that's going to achieve what you want with something like `x-robots-tag`, but when you inspect your object in the AWS S3 console you'll be able to see that metadata.

Hope that helps.
