### ISSUE TITLE
Is there a filter hook to disable S3 to local url replacement?

### ISSUE THREAD

**Issue by sseepuri** [deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks#9]
We have a unique case in our environment where we don't want the urls to be converted back from S3 to local in the database - so this plugin used to work fine for us before the updates in 1.2 (https://deliciousbrains.com/wp-offload-s3-1-2-released/). Now that the behavior has changed, is it possible to turn off the S3 to local conversion on our end? If not, is it possible to expose that filter hook?

**Comment by ianmjones** [comment]
@sseepuri Please can you expand on your use-case for wanting to store S3 URLs in the database?

**Comment by sseepuri** [comment]
Our environment is set up such that the posts are created directly in our prod env whereas page content and code changes are made in staging environment. So for a prod deploy, we first export the posts from prod, import and sync them into staging, and then deploy the entire staging env to prod. This ends up leaving the local URLs in prod at the end, breaking images in our blogs. As you can imagine, this used to work when the S3 URLs were being stored in the database

**Comment by ianmjones** [comment]
@sseepuri I think you need to take a look at https://deliciousbrains.com/wp-migrate-db-pro/ for a super simple way of pushing content from one site to another with URLs being properly updated for the target site along the way!

We have no plans on reversing our decision to filter local URLs to S3 URLs on page render and do not envision adding a feature that optionally supports embedded S3 URLs either.
